name: Package Lock Diff

on:
  pull_request:
    paths:
      - 'pnpm-lock.yaml'
      - '**/pnpm-lock.yaml'

jobs:
  package-lock-diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Package lock diff
        uses: ./action
        with:
          filename: 'pnpm-lock.yaml'
          resolver: 'pnpm'
